vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images: 
            uri_prefix: /public/uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true


